#!/usr/bin/env python3
"""Walk-forward of the frozen strategy config over the multi-year history (HANDOFF.md step 3).

  python walkforward.py data/BTCUSDT_4h.csv > WALKFORWARD.md

troid-shadow-1's parameters were chosen on 2026-01-08 -> 2026-09-21, the frozen sample
in data/btc_4h.csv. Every year before that is a holdout the config never saw. One
continuous run over the whole file with challenge accounting off (expectancy per trade is
the statistic), trades bucketed by exit year. A bucket under 30 trades is reported as
insufficient, not as a number. Nothing here changes the config; a changed config is a new
strategy with a new journal.

Also writes results/walkforward_<SYMBOL>.json with every bucket's numbers.
"""
from __future__ import annotations
import sys, csv, json, math, statistics, datetime as dt
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
import engine as E
import engine_v2 as V
import site_text
from forward import apply_config, CFG            # the one config -> engine mapping

FIT_START, FIT_END = dt.date(2026, 1, 8), dt.date(2026, 9, 21)   # the frozen sample
MIN_N = 30


def feed_line(path):
    for r in csv.reader(open(path)):
        if r and r[0].startswith("#"):
            return r[0].lstrip("# ")
    return "o,h,l,c file"


def stats(trades):
    rs = [t["r"] for t in trades]; n = len(rs)
    out = dict(n=n, flagged=sum(1 for t in trades if t["filled"]))
    if n < 2:
        return out
    pnl = [t["pnl"] for t in trades]
    gw, gl = sum(x for x in pnl if x > 0), -sum(x for x in pnl if x < 0)
    m, sd = statistics.mean(rs), statistics.stdev(rs); se = sd / math.sqrt(n)
    out.update(exp=m, sd=sd, se=se, lo=m - 1.96 * se, hi=m + 1.96 * se,
               pf=(gw / gl if gl else float("inf")), win=100 * sum(1 for x in pnl if x > 0) / n,
               net=sum(pnl), fills_w=statistics.mean([t["fills"] for t in trades if t["pnl"] > 0] or [0]),
               fills_l=statistics.mean([t["fills"] for t in trades if t["pnl"] <= 0] or [0]))
    return out


def row(label, st, months, filled_bars=""):
    tpm = st["n"] / months if months else 0
    if st["n"] < MIN_N:
        return f"| {label} | {st['n']} | {tpm:.1f} | insufficient (n < {MIN_N}) | | | | | {st['flagged']} | {filled_bars} |"
    return (f"| {label} | {st['n']} | {tpm:.1f} | {st['win']:.0f}% | {st['exp']:+.3f} | {st['se']:.3f} | "
            f"[{st['lo']:+.3f}, {st['hi']:+.3f}] | {st['pf']:.2f} | {st['flagged']} | {filled_bars} |")


def main(path):
    apply_config()
    bars = E.load_bars(path)
    e20, e120, atr = E.indicators(bars)
    sigs = V.build_signals(bars, e20, e120, atr)
    warm = max(E.EMA_TREND + E.TREND_SLOPE_BARS, V.RANGE_BARS) + 1
    r = V.run(bars, sigs, warm, challenge=False, risk_pct=CFG["risk_pct"], atr=atr)
    flat = {i for i, b in enumerate(bars) if b[0] == b[1] == b[2] == b[3]}

    def when(i):
        return dt.datetime.fromtimestamp(E.T0 + i * E.STEP, dt.timezone.utc)

    for t in r.trades:
        t["when"] = when(t["bar"])
        t["filled"] = any(i in flat for i in range(t["bar"] - t["bars"], t["bar"] + 1))

    years = sorted({when(i).year for i in range(warm, len(bars))})
    buckets = {}
    for y in years:
        idx = [i for i in range(warm, len(bars)) if when(i).year == y]
        buckets[y] = dict(trades=[t for t in r.trades if t["when"].year == y],
                          months=len(idx) * 4 / 24 / 30.44, filled_bars=sum(1 for i in idx if i in flat))
    hold = [t for t in r.trades if t["when"].date() < FIT_START]
    fit = [t for t in r.trades if FIT_START <= t["when"].date() <= FIT_END]
    after = [t for t in r.trades if t["when"].date() > FIT_END]
    hold_months = sum(1 for i in range(warm, len(bars)) if when(i).date() < FIT_START) * 4 / 24 / 30.44
    fit_months = sum(1 for i in range(warm, len(bars)) if FIT_START <= when(i).date() <= FIT_END) * 4 / 24 / 30.44
    after_months = sum(1 for i in range(warm, len(bars)) if when(i).date() > FIT_END) * 4 / 24 / 30.44
    sym = Path(path).stem.replace("_4h", "")

    print(f"# Walk-forward — {sym} 4h, {len(bars)} bars, {when(0):%Y-%m-%d} -> {when(len(bars)-1):%Y-%m-%d}\n")
    print("**Generated by `walkforward.py`. Do not hand-edit — regenerate.**\n")
    print(site_text.hypo_md(no_edge=site_text.NO_EDGE_SHORT + " The holdout rows below are the measurement — MEASURED, inside noise."))
    print(f"Data: `{path}` — {feed_line(path).rstrip('.')}. Forward-filled bars in the file: {len(flat)}.\n")
    print(f"Strategy: `{CFG['name']}` from `strategy_config.json`, unchanged. Its parameters were chosen on "
          f"{FIT_START} -> {FIT_END} (the frozen sample). Every earlier year is a holdout the config never saw. "
          f"One continuous run, challenge accounting off, {CFG['risk_pct']*100:.1f}% risk per trade, "
          f"trades bucketed by exit time. Buckets under {MIN_N} trades are insufficient, not numbers. "
          f"`flagged` counts trades that held through a forward-filled bar.\n")
    print("| bucket | n | trades/mo | win | exp R | SE | 95% CI | PF | flagged trades | filled bars |")
    print("|---|---|---|---|---|---|---|---|---|---|")
    for y in years:
        b = buckets[y]
        tag = " (fit sample)" if FIT_START.year == y else ""
        print(row(f"{y}{tag}", stats(b["trades"]), b["months"], b["filled_bars"] or ""))
    print(row(f"**holdout, before {FIT_START}**", stats(hold), hold_months))
    print(row(f"**fit sample, {FIT_START} -> {FIT_END}**", stats(fit), fit_months))
    if after:
        print(row(f"after {FIT_END} (live tail)", stats(after), after_months))
    print()
    hs, fs = stats(hold), stats(fit)
    print("## Reading it\n")
    if hs["n"] >= MIN_N:
        verdict = ("excludes zero" if hs["lo"] > 0 or hs["hi"] < 0 else "contains zero")
        print(f"- Holdout: n = {hs['n']}, {hs['exp']:+.3f}R, SE {hs['se']:.3f}R, 95% CI [{hs['lo']:+.3f}R, {hs['hi']:+.3f}R] — {verdict}.")
    else:
        print(f"- Holdout: n = {hs['n']} — insufficient.")
    if fs["n"] >= 2:
        print(f"- Fit sample, re-run inside the continuous history: n = {fs['n']}, {fs['exp']:+.3f}R. This differs from the "
              f"frozen sample's own replay because the indicators carry real history into 2026 instead of a warm-up, "
              f"and the position state carries over from the prior year.")
    print(f"- Per-year rows are the regime dependence HANDOFF.md asks for. Read the neighbourhood, not the best cell.")
    print(f"- Fills W/L on the holdout: {hs.get('fills_w', 0):.2f} / {hs.get('fills_l', 0):.2f}" if hs["n"] >= MIN_N else "")

    out = Path(__file__).parent / "results"; out.mkdir(exist_ok=True)
    dump = {"symbol": sym, "bars": len(bars), "first": when(0).isoformat(), "last": when(len(bars)-1).isoformat(),
            "config": CFG["name"], "fit_sample": [FIT_START.isoformat(), FIT_END.isoformat()],
            "forward_filled_bars": len(flat),
            "years": {str(y): dict(stats(b["trades"]), months=b["months"], filled_bars=b["filled_bars"]) for y, b in buckets.items()},
            "holdout": dict(stats(hold), months=hold_months), "fit": dict(stats(fit), months=fit_months),
            "after": dict(stats(after), months=after_months)}
    (out / f"walkforward_{sym}.json").write_text(json.dumps(dump, indent=1, default=str))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "data/BTCUSDT_4h.csv")
